version: '3'

# IF CHANGES ARE MADE IN THIS FILE PLEASE MAKE SURE THAT THE
# COMPILATION .SH SCRIPT IS NOT COMPROMISED
services:
  main_dispatcher:
    build: .
    image: main_dispatcher:srsc_p2
    ports:
      - "8080:8080"
    command: ["java" ,"-cp" ,"target/srsc-p2-mvn-1.0.jar", "srsc.servers.MainDispatcher.MainDispatcherServer"]
    volumes:
      - ./certs/mdCrypto:/app/certs/mdCrypto
      - ./configs/tlsConfig:/app/configs/tlsConfig
  authentication:
    build: .
    image: auth_server:srsc_p2
    ports:
      - "8081:8081"
    command: ["java" ,"-cp" ,"target/srsc-p2-mvn-1.0.jar:lib/sqlite-jdbc-3.44.0.0.jar:lib/slf4j-api-1.7.36.jar", "srsc.servers.Authentication.AuthenticationServer"]
    volumes:
      - ./certs/asCrypto:/app/certs/asCrypto
      - ./configs/auth_server.conf:/app/configs/auth_server.conf
      - ./configs/tlsConfig/server.conf:/app/configs/tlsConfig/server.conf
      - ./lib:/app/lib
  access_control:
    build: .
    image: access_control:srsc_p2
    ports:
      - "8082:8082"
    command: ["java" ,"-cp" ,"target/srsc-p2-mvn-1.0.jar:lib/sqlite-jdbc-3.44.0.0.jar:lib/slf4j-api-1.7.36.jar", "srsc.servers.AccessControl.AccessControlServer"]
    volumes:
      - ./certs/acCrypto:/app/certs/acCrypto
      - ./configs/access_control_server.conf:/app/configs/access_control_server.conf
      - ./configs/tlsConfig/server.conf:/app/configs/tlsConfig/server.conf
      - ./lib:/app/lib
  storage_service:
    build: .
    image: storage_service:srsc_p2
    ports:
      - "8083:8083"
    command: ["java" ,"-cp" ,"target/srsc-p2-mvn-1.0.jar", "srsc.servers.StorageService.StorageServiceServer"]
    volumes:
      - ./certs/ssCrypto:/app/certs/ssCrypto
      - ./configs/storage_server.conf:/app/configs/storage_server.conf
      - ./configs/tlsConfig/server.conf:/app/configs/tlsConfig/server.conf