version: '3'

services:
    maindispatcher:
        image: main_dispatcher
        ports:
          - "8080:8080"
    authentication:
      image: authentication_server
      ports:
        - "8081:8081"
    accesscontrol:
      image: access_control
      ports:
        - "8082:8082"
    storageservice:
      image: storage_service
      ports:
        - "8083:8083"